spring:
  profiles:
    active: dev
    
    include: local
    
    default: uat

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    type: org.apache.commons.dbcp2.BasicDataSource
    url: jdbc:mysql:///springdb
    username: root
    
---
#dev
spring:
  profiles: dev
  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    type: org.apache.commons.dbcp2.BasicDataSource
    url: jdbc:mysql:///springdb
    username: root

---
#test
spring:
  profiles: test
  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    type: org.apache.tomcat.jdbc.pool.DataSource
    url: jdbc:mysql:///springdb
    username: root

---
#local
spring:
  profiles: local
  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    type: oracle.ucp.jdbc.PoolDataSourceImpl
    url: jdbc:mysql:///springdb
    username: root
    
---
#uat
spring:
  profiles: uat
  
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    password: tiger
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: scott
    
   
---
#prod
spring:
  profiles: prod
  
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: tiger
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: scott

